# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/kieranjames.yml

## desktop environments
  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/keybindings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/nautilus.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/shell_settings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/terminal.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/tracker.yml
    when: gnome is defined and gnome == true

  ## system setup
  - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/authenticator.yml
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/cryptomator.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/joplin.yml
  - import_tasks: software/mariadb.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/rambox.yml
  - import_tasks: software/skype.yml
  - import_tasks: software/slack.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/steam.yml
  - import_tasks: software/teams.yml

  rescue:
    - set_fact: task_failed=true
