- name: software | rambox | install package
  tags: packages,rambox,snap,workstation-packages
  snap:
    name:  rambox
    channel: latest/edge
    state: present
  when:
    - ansible_distribution != "Archlinux"
    - rambox is defined
    - rambox == true
  
- name: software | rambox | remove package
  tags: packages,rambox,snap,workstation-packages
  snap:
    name:  rambox
    state: absent
  when:
    - ansible_distribution != "Archlinux"
    - rambox is defined
    - rambox == false