- name: gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  copy:
    src: gnome/wallpaper.jpg
    dest: /usr/share/backgrounds/kieranjames-wallpaper.jpg
    owner: root
    group: root
    mode: 0644

- name: gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/kieranjames-wallpaper.jpg'"

- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

# - name: gnome | appearance | copy lock screen background file
#   tags: gnome,gnome-lockscreen
#   copy:
#     src: files/gnome/lockscreen.jpg
#     dest: /usr/share/backgrounds/kieranjames-lockscreen.jpg
#     owner: root
#     group: root
#     mode: 0644

- name: gnome | appearance | set lock screen background
  tags: gnome,gnome-lockscreen
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///usr/share/backgrounds/kieranjames-wallpaper.jpg'"

- name: gnome | appearance | set lock screen background position
  tags: gnome,gnome-lockscreen
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-options"
    value: "'zoom'"

- name: gnome | appearance | set app-folders
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folder-children"
    value: "['System', 'Utility', 'Office']"

- name: gnome | appearance | set label of the system directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/System/name"
    value: "'System'"

- name: gnome | appearance | set applications within system directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/System/apps"
    value: "['org.gnome.Settings.desktop', 'gnome-system-monitor.desktop', 'org.gnome.PowerStats.desktop', 'org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'gparted.desktop', 'org.gnome.Extensions.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.Terminal.desktop', 'bssh.desktop', 'bvnc.desktop', 'avahi-discover.desktop', 'nm-connection-editor.desktop', 'org.gnome.Logs.desktop']"

- name: gnome | appearance | set label of the utility directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/Utility/name"
    value: "'Utility'"

- name: gnome | appearance | set applications within utility directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/Utility/apps"
    value: "['htop.desktop', 'timeshift-gtk.desktop', 'ca.desrt.dconf-editor.desktop', 'org.gnome.gedit.desktop', 'org.gnome.eog.desktop', 'org.gnome.Evince.desktop', 'org.gnome.FileRoller.desktop', 'org.gnome.font-viewer.desktop', 'simple-scan.desktop', 'org.gnome.Totem.desktop', 'org.gnome.Weather.desktop', 'cups.desktop', 'org.gnome.Characters.desktop', 'qv4l2.desktop', 'qvidcap.desktop', 'yelp.desktop']"

- name: gnome | appearance | set label of the office directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/Office/name"
    value: "'Office'"

- name: gnome | appearance | set applications within office directory
  tags: gnome,app-folders
  become_user: kieranjames
  dconf:
    key: "/org/gnome/desktop/app-folders/folders/Office/apps"
    value: "['org.libreoffice.LibreOffice.desktop', 'org.libreoffice.LibreOffice.writer.desktop', 'org.libreoffice.LibreOffice.calc.desktop', 'org.libreoffice.LibreOffice.impress.desktop', 'org.libreoffice.LibreOffice.base.desktop', 'org.libreoffice.LibreOffice.draw.desktop', 'org.libreoffice.LibreOffice.math.desktop']"

- name: gnome | appearance | set favorite apps
  tags: gnome,favorite-apps
  become_user: kieranjames
  dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['code.desktop', 'io.dbeaver.DBeaverCommunity.desktop', 'com.google.Chrome.desktop', 'com.slack.Slack.desktop', 'com.spotify.Client.desktop', 'org.gnome.Geary.desktop', 'org.gnome.Nautilus.desktop']"

- name: gnome | appearance | set app layout
  tags: gnome,app-layout
  become_user: kieranjames
  dconf:
    key: "/org/gnome/shell/app-picker-layout"
    value: "[{'System': <{'position': <0>}>, 'Utility': <{'position': <1>}>, 'Office': <{'position': <2>}>, 'org.gnome.Software.desktop': <{'position': <3>}>, 'org.gnome.Contacts.desktop': <{'position': <4>}>, 'org.gnome.Calendar.desktop': <{'position': <5>}>, 'org.gnome.Calculator.desktop': <{'position': <6>}>, 'com.bitwarden.desktop.desktop': <{'position': <7>}>, 'com.belmoussaoui.Authenticator.desktop': <{'position': <8>}>, 'org.cryptomator.Cryptomator.desktop': <{'position': <9>}>, 'org.gnome.Boxes.desktop': <{'position': <10>}>, 'net.cozic.joplin_desktop.desktop': <{'position': <11>}>, 'steam.desktop': <{'position': <12>}>, 'shotwell.desktop': <{'position': <13>}>, 'org.mozilla.firefox.desktop': <{'position': <14>}>, 'org.ferdium.Ferdium.desktop': <{'position': <15>}>}]"
