# Note: Some of these packages are disabled, they depend on tracker which is currently being disabled
- name: gnome | packages | install gnome packages
  tags: gnome,gnome-packages
  package:
    name:
      - eog
      - file-roller
      - "{{ gdm_package }}"
      - gedit
      - gnome-backgrounds
      - gnome-boxes
      - gnome-control-center
      - gnome-disk-utility
      - gnome-power-manager
      - gnome-remote-desktop
      - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-terminal
      - gnome-tweaks
      - nautilus

- name: gnome | packages | remove gnome packages
  tags: gnome,gnome-packages
  package:
    state: absent
    name:
      - gnome-console
      - gnome-text-editor
      - gnome-maps
      - gnome-music
      - gnome-photos
      - gnome-clocks
      - cheese
      - gvim
      - epiphany

- name: gnome | packages | install flatpak support in gnome software
  tags: gnome,gnome-packages
  package:
    name:
    - gnome-software-plugin-flatpak
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: gnome | packages | enable and start gdm
  tags: autofs,system,system setup
  service:
    name: gdm
    enabled: true
    state: started
