- name: system setup | repositories | update arch linux repository mirrorlist
  tags: packages,repositories
  copy:
    src: files/system_setup/arch_mirrorlist
    dest: /etc/pacman.d/mirrorlist
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Archlinux"

- name: system setup | repositories | add ignored packages for archlinux hosts
  tags: packages,repositories
  lineinfile:
      dest: /etc/pacman.conf
      regexp: "^#?IgnorePkg"
      line: "IgnorePkg   = ansible linux linux-headers linux-lts linux-lts-headers"
  when: ansible_distribution == "Archlinux"

- name: system setup | repositories | install package management tools (debian-based)
  tags: packages,system,settings
  package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
